### Numpy Array Refresh

In [1]:
import numpy as np
np.random.seed(123)  # seeding for reproducibility

x1 = np.random.randint(12, size=(1, 2, 3))  # Three-dimensional array

In [2]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  3
x1 shape: (1, 2, 3)
x1 size:  6


In [3]:
print(x1)

[[[ 2  2  6]
  [ 1  3 10]]]


Array datatype

In [4]:
x1.dtype

dtype('int32')

In [5]:
x2 = np.random.randint(10, size=6)

In [6]:
x2

array([9, 6, 1, 0, 1, 9])

To access elements of an array

In [7]:
x2[0]

9

In [8]:
x2[3]

0

In [9]:
x2[-1]

9

In [10]:
x1

array([[[ 2,  2,  6],
        [ 1,  3, 10]]])

In [11]:
x1[0,0]

array([2, 2, 6])

Slicing Array

In [12]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [13]:
a[:0]

array([], dtype=int32)

In [14]:
a[:5]

array([0, 1, 2, 3, 4])

In [15]:
a[:-1]

array([0, 1, 2, 3])

In [16]:
a[-1:]

array([4])

In [17]:
a[::-1]

array([4, 3, 2, 1, 0])

In [18]:
y = np.random.randint(10, size=(3, 4))

In [19]:
y

array([[0, 0, 9, 3],
       [4, 0, 0, 4],
       [1, 7, 3, 2]])

In [20]:
y[:2, :1]

array([[0],
       [4]])

In [21]:
y[:3, :4] 

array([[0, 0, 9, 3],
       [4, 0, 0, 4],
       [1, 7, 3, 2]])

In [22]:
y[:1, ::2]

array([[0, 9]])

In [23]:
y[:3, ::2]

array([[0, 9],
       [4, 0],
       [1, 3]])

In [24]:
y[::-1, ::-1]

array([[2, 3, 7, 1],
       [4, 0, 0, 4],
       [3, 9, 0, 0]])

Array Reshaping

In [25]:
r = np.arange(1, 10).reshape((3, 3))
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [27]:
x.shape

(3,)

In [28]:
x.size

3

In [29]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [30]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])