In [0]:
import torch

In [0]:
torch.version.__version__

'1.5.0+cu101'

In [0]:
a = torch.ones(3,3)

In [0]:
b = torch.ones(3,3)

In [0]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [0]:
a = a.to('cuda')
b = b.to('cuda')
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

Tensor representation of data

Columnar data

In [0]:
import csv
import numpy as np
import torch

In [0]:
from sklearn import datasets

In [0]:
wine = datasets.load_wine()

In [0]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [0]:
X = wine.data

In [0]:
Y=  wine.target

In [0]:
import pandas as pd

In [0]:
wine_df = pd.DataFrame(X, columns = wine.feature_names)

In [0]:
wine_df

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [0]:
wine_df.shape

(178, 13)

Torch Tensor -  Numpy conversion

In [0]:
wine_torch = torch.from_numpy(X)

In [0]:
wine_torch.shape, wine_torch.type()

(torch.Size([178, 13]), 'torch.DoubleTensor')

In [0]:
data = wine_torch

In [0]:
data, data.shape

(tensor([[1.4230e+01, 1.7100e+00, 2.4300e+00,  ..., 1.0400e+00, 3.9200e+00,
          1.0650e+03],
         [1.3200e+01, 1.7800e+00, 2.1400e+00,  ..., 1.0500e+00, 3.4000e+00,
          1.0500e+03],
         [1.3160e+01, 2.3600e+00, 2.6700e+00,  ..., 1.0300e+00, 3.1700e+00,
          1.1850e+03],
         ...,
         [1.3270e+01, 4.2800e+00, 2.2600e+00,  ..., 5.9000e-01, 1.5600e+00,
          8.3500e+02],
         [1.3170e+01, 2.5900e+00, 2.3700e+00,  ..., 6.0000e-01, 1.6200e+00,
          8.4000e+02],
         [1.4130e+01, 4.1000e+00, 2.7400e+00,  ..., 6.1000e-01, 1.6000e+00,
          5.6000e+02]], dtype=torch.float64), torch.Size([178, 13]))

In [0]:
target = torch.from_numpy(Y)

In [0]:
target

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
target, target.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), torch.Size([178]))

In [0]:
data_mean = torch.mean(data, dim=0)

In [0]:
data_mean

tensor([1.3001e+01, 2.3363e+00, 2.3665e+00, 1.9495e+01, 9.9742e+01, 2.2951e+00,
        2.0293e+00, 3.6185e-01, 1.5909e+00, 5.0581e+00, 9.5745e-01, 2.6117e+00,
        7.4689e+02], dtype=torch.float64)

In [0]:
data_var = torch.var(data, dim=0)

In [0]:
data_var

tensor([6.5906e-01, 1.2480e+00, 7.5265e-02, 1.1153e+01, 2.0399e+02, 3.9169e-01,
        9.9772e-01, 1.5489e-02, 3.2759e-01, 5.3744e+00, 5.2245e-02, 5.0409e-01,
        9.9167e+04], dtype=torch.float64)

In [0]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

tensor([[ 1.5143, -0.5607,  0.2314,  ...,  0.3612,  1.8427,  1.0102],
        [ 0.2456, -0.4980, -0.8257,  ...,  0.4049,  1.1103,  0.9625],
        [ 0.1963,  0.0212,  1.1062,  ...,  0.3174,  0.7864,  1.3912],
        ...,
        [ 0.3318,  1.7398, -0.3883,  ..., -1.6076, -1.4813,  0.2798],
        [ 0.2086,  0.2271,  0.0127,  ..., -1.5638, -1.3968,  0.2957],
        [ 1.3912,  1.5787,  1.3614,  ..., -1.5201, -1.4249, -0.5935]],
       dtype=torch.float64)